[build]
base = "docs"                       # <- run all steps inside docs/
command = "npm ci && npm run docs:build"
publish = ".vitepress/dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
