name: E2E Tests

on:
  # Allow manual trigger
  workflow_dispatch:

  # Run weekly on Mondays at 8 AM UTC
  schedule:
    - cron: '0 8 * * 1'

  # Run on push to main/master (optional, can be removed if you only want manual/scheduled runs)
  push:
    branches: [ main, master ]
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'

jobs:
  e2e:
    name: E2E Tests against Live Trello API
    runs-on: ubuntu-latest

    # Only run if secrets are available
    if: ${{ secrets.TRELLO_API_KEY != '' && secrets.TRELLO_TOKEN != '' }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-e2e-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-e2e-
          ${{ runner.os }}-go-

    - name: Download dependencies
      run: go mod download

    - name: Run E2E tests
      env:
        TRELLO_API_KEY: ${{ secrets.TRELLO_API_KEY }}
        TRELLO_TOKEN: ${{ secrets.TRELLO_TOKEN }}
      run: |
        echo "Running E2E tests against live Trello API..."
        go test -v -timeout 30m -run TestE2EAllCommands ./...

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: e2e-test-results
        path: |
          *.log
          coverage.txt
        retention-days: 30
