name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., v1.0.0)'
        required: true
        type: string

env:
  GO_VERSION: '1.23'

jobs:
  build:
    name: Build Binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            goos: linux
            goarch: amd64
            suffix: linux-amd64
          - os: ubuntu-latest
            goos: linux
            goarch: arm64
            suffix: linux-arm64
          - os: macos-latest
            goos: darwin
            goarch: amd64
            suffix: darwin-amd64
          - os: macos-latest
            goos: darwin
            goarch: arm64
            suffix: darwin-arm64
          - os: windows-latest
            goos: windows
            goarch: amd64
            suffix: windows-amd64.exe
          - os: windows-latest
            goos: windows
            goarch: arm64
            suffix: windows-arm64.exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Get dependencies
        run: go mod download

      - name: Run tests
        run: go test ./...

      - name: Build binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          go build -ldflags="-s -w -X main.version=${{ github.ref_name }}" -o trlo-${{ matrix.suffix }} .

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: trlo-${{ matrix.suffix }}
          path: trlo-${{ matrix.suffix }}

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Create checksums
        run: |
          cd trlo-linux-amd64
          sha256sum trlo-linux-amd64 > ../checksums.txt
          cd ../trlo-linux-arm64
          sha256sum trlo-linux-arm64 >> ../checksums.txt
          cd ../trlo-darwin-amd64
          shasum -a 256 trlo-darwin-amd64 >> ../checksums.txt
          cd ../trlo-darwin-arm64
          shasum -a 256 trlo-darwin-arm64 >> ../checksums.txt
          cd ../trlo-windows-amd64.exe
          sha256sum trlo-windows-amd64.exe >> ../checksums.txt
          cd ../trlo-windows-arm64.exe
          sha256sum trlo-windows-arm64.exe >> ../checksums.txt

      - name: Extract version
        id: version
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "version=${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          fi

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: Trello CLI ${{ steps.version.outputs.version }}
          body: |
            ## Trello CLI ${{ steps.version.outputs.version }}

            A comprehensive Trello CLI tool optimized for LLM integration.

            ### Installation

            #### Homebrew (macOS)
            ```bash
            brew tap danbruder/tap
            brew install trlo
            ```

            #### Manual Installation
            1. Download the appropriate binary for your platform
            2. Make it executable: `chmod +x trlo-*`
            3. Move to your PATH: `sudo mv trlo-* /usr/local/bin/trlo`

            ### Checksums
            ```
            ${{ github.workspace }}/checksums.txt
            ```

            ### What's New
            - See [CHANGELOG.md](https://github.com/danbruder/trlo/blob/main/CHANGELOG.md) for detailed changes
          files: |
            trlo-linux-amd64/trlo-linux-amd64
            trlo-linux-arm64/trlo-linux-arm64
            trlo-darwin-amd64/trlo-darwin-amd64
            trlo-darwin-arm64/trlo-darwin-arm64
            trlo-windows-amd64.exe/trlo-windows-amd64.exe
            trlo-windows-arm64.exe/trlo-windows-arm64.exe
            checksums.txt
          draft: false
          prerelease: false
